FROM golang:1.26-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o api-server ./api

FROM alpine:3.21

WORKDIR /app

COPY --from=builder /app/api-server ./api-server

EXPOSE 8889

CMD ["./api-server"]
