FROM golang:1.26-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o item-server ./rpc/item

FROM alpine:3.21

WORKDIR /app

COPY --from=builder /app/item-server ./item-server

EXPOSE 8888

CMD ["./item-server"]
