// Code generated by Kitex v0.16.3. DO NOT EDIT.

package stock

import (
	"context"
	"example_shop/kitex_gen/example/shop/base"

	"github.com/cloudwego/prutal"
)

type GetItemStockReq struct {
	ItemId int64 `protobuf:"varint,1,opt,name=item_id" json:"item_id,omitempty"`
}

func (x *GetItemStockReq) Reset() { *x = GetItemStockReq{} }

func (x *GetItemStockReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetItemStockReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetItemStockReq) GetItemId() int64 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

type GetItemStockResp struct {
	Stock    int64          `protobuf:"varint,1,opt,name=stock" json:"stock,omitempty"`
	BaseResp *base.BaseResp `protobuf:"bytes,255,opt,name=base_resp" json:"base_resp,omitempty"`
}

func (x *GetItemStockResp) Reset() { *x = GetItemStockResp{} }

func (x *GetItemStockResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetItemStockResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetItemStockResp) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *GetItemStockResp) GetBaseResp() *base.BaseResp {
	if x != nil {
		return x.BaseResp
	}
	return nil
}

type StockService interface {
	GetItemStock(ctx context.Context, req *GetItemStockReq) (res *GetItemStockResp, err error)
}
