// Code generated by Kitex v0.16.3. DO NOT EDIT.

package stockservice

import (
	"context"
	"errors"
	stock "example_shop/kitex_gen/example/shop/stock"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "github.com/cloudwego/prutal"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"GetItemStock": kitex.NewMethodInfo(
		getItemStockHandler,
		newGetItemStockArgs,
		newGetItemStockResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	stockServiceServiceInfo                = NewServiceInfo()
	stockServiceServiceInfoForClient       = NewServiceInfoForClient()
	stockServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return stockServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return stockServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return stockServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "StockService"
	handlerType := (*stock.StockService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "example.shop.stock",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.16.3",
		Extra:           extra,
	}
	return svcInfo
}

func getItemStockHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(stock.GetItemStockReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(stock.StockService).GetItemStock(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetItemStockArgs:
		success, err := handler.(stock.StockService).GetItemStock(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetItemStockResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetItemStockArgs() interface{} {
	return &GetItemStockArgs{}
}

func newGetItemStockResult() interface{} {
	return &GetItemStockResult{}
}

type GetItemStockArgs struct {
	Req *stock.GetItemStockReq
}

func (p *GetItemStockArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetItemStockArgs) Unmarshal(in []byte) error {
	msg := new(stock.GetItemStockReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetItemStockArgs_Req_DEFAULT *stock.GetItemStockReq

func (p *GetItemStockArgs) GetReq() *stock.GetItemStockReq {
	if !p.IsSetReq() {
		return GetItemStockArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetItemStockArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetItemStockArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetItemStockResult struct {
	Success *stock.GetItemStockResp
}

var GetItemStockResult_Success_DEFAULT *stock.GetItemStockResp

func (p *GetItemStockResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetItemStockResult) Unmarshal(in []byte) error {
	msg := new(stock.GetItemStockResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetItemStockResult) GetSuccess() *stock.GetItemStockResp {
	if !p.IsSetSuccess() {
		return GetItemStockResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetItemStockResult) SetSuccess(x interface{}) {
	p.Success = x.(*stock.GetItemStockResp)
}

func (p *GetItemStockResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetItemStockResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) GetItemStock(ctx context.Context, Req *stock.GetItemStockReq) (r *stock.GetItemStockResp, err error) {
	var _args GetItemStockArgs
	_args.Req = Req
	var _result GetItemStockResult
	if err = p.c.Call(ctx, "GetItemStock", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
