// Code generated by Kitex v0.16.3. DO NOT EDIT.

package item

import (
	"context"
	"example_shop/kitex_gen/example/shop/base"

	"github.com/cloudwego/prutal"
)

type Item struct {
	Id          int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Title       string `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	Stock       int64  `protobuf:"varint,4,opt,name=stock" json:"stock,omitempty"`
}

func (x *Item) Reset() { *x = Item{} }

func (x *Item) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *Item) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *Item) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Item) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Item) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Item) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

type GetItemReq struct {
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (x *GetItemReq) Reset() { *x = GetItemReq{} }

func (x *GetItemReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetItemReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetItemReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetItemResp struct {
	Item     *Item          `protobuf:"bytes,1,opt,name=item" json:"item,omitempty"`
	BaseResp *base.BaseResp `protobuf:"bytes,255,opt,name=base_resp" json:"base_resp,omitempty"`
}

func (x *GetItemResp) Reset() { *x = GetItemResp{} }

func (x *GetItemResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetItemResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetItemResp) GetItem() *Item {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *GetItemResp) GetBaseResp() *base.BaseResp {
	if x != nil {
		return x.BaseResp
	}
	return nil
}

type ItemService interface {
	GetItem(ctx context.Context, req *GetItemReq) (res *GetItemResp, err error)
}
