// Copyright 2024 CloudWeGo Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package example.shop.stock;

option go_package = "example_shop/kitex_gen/example/shop/stock;stock";

import "base.proto";

message GetItemStockReq {
  int64 item_id = 1;
}

message GetItemStockResp {
  int64 stock = 1;
  example.shop.base.BaseResp base_resp = 255;
}

service StockService {
  rpc GetItemStock(GetItemStockReq) returns (GetItemStockResp);
}
