// Code generated by Kitex v0.16.3. DO NOT EDIT.

package base

import "github.com/cloudwego/prutal"

type BaseResp struct {
	Code string `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
}

func (x *BaseResp) Reset() { *x = BaseResp{} }

func (x *BaseResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *BaseResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *BaseResp) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *BaseResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}
